name = "StackUp!"

[store]
id="com.github.adbenitez.StackUp"
version_name=1.0
version_code=3
author="adbenitez"
author_email="adbenitez@nauta.cu"
description="Tower building game. Place blocks by clicking, tapping or pressing the spacebar"